---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - namspace.yaml
  - configmap.yaml
  - service.yaml
  - secret.yaml
namespace: grafana
namePrefix: grafana-
commonLabels:
  app.kubernetes.io/name: grafana
  app.kubernetes.io/component: test-automation-jmeter-grafana
  app.kubernetes.io/part-of: nft-jmeter-grafana