apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-cm
data:
  domain.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQClQzIRweHN5id6
    lzrYFB4XKOVVyxsh57ewk7bCnzZTCaOs4wddgWna9kjobAz2XuPsAh6wINoHgl25
    ORRNMEfBTY9ekkA4cJBCMbmRFeV+FqtMs2F6YTv7zHts2ZiBE7pGVxjk0bIz9PD0
    iQhzTrz5yXeXk4aNgzAVIzX7WuCRtSDJRpNKJk0eSxzI+R0uO4vBlnlttgLQXICX
    Uoml8fJjKV2iLBUfu6J6Y5TO2NLGnP1EIDkxW8FamDl6cnAAYunbYImR3CI98GQh
    D3K+HIwUS1Z5UK8Bh9YsFWXooDpSjMOdPFvUMCu1p7B1O9ehDjIHyxs4HkzfqiYQ
    o9kI/lFZAgMBAAECggEAVM+sRWKroEAqKIat4zBH1Pje4O2P6hGBunPEChMtDOZY
    giQspncAvSdBeU3iRRmjfH4GA7uISOxFbwX0/jv1xyUnm5AQtyZFUkM0iVmkYdX+
    aSlxsB1wbCOff9gXpL5cDTcrhlp7SqC8e7JLjOlun/4disNh/QPDTEW6sVkNAJkR
    jL/ZuTslrIbipI9SEKGnCiImBVL1m4eICArWMYPbO63X7HciVsCjAR8W2XZyiME+
    92jbEkA9ROh6NkRJKklGjf2v52i9l66N5Ws2YeBr1fU3gccDBZXgN9+RaEL9DTHB
    Tkh2CneUkIY5LFmG/VdjjpGwz5q2xNPOd4U5fPwktQKBgQDVaIUuBjiZMf6FZhH1
    F3lH76zNHiQEHqmSPziiicmWn+Du3Ev4IAyR5sUNCx5HPl3BrMquLTOTRQ1FyRc7
    rOBhmWp34sQjBEE475vzfr3pP/t5mXvFjtjGvWlduq4R1Y/t3lrYdWK6pAvcrWfD
    Jmw4K7hBJyaRiK3brSOvNxkxjwKBgQDGPs4G9RTL7MBqVH6Zav+OSR2+IDvse8j+
    IkAUo8XMUZSoc3rP9oElX5AhJCJ1T//I6va+rspyeRa+wZpqS6bBxrpfUEtYOWbJ
    L9BYMxIkVlzl2yWJAy7Ey47Bdi8xZmXg4Y2rUvJRysMFhJE3pT89Tl37ldyb4niG
    QE6cqWWKlwKBgE4ZYiPlwvDNiwfmwsufO5NH80VdsnCPiB8tY9yX8F5fREIl/Odh
    UzhR6+tKFlqcSFOImOQFRsquipzvasE8EyGks4IMSxtFg1kC11/VEks6Tx3BPbqe
    /FY/G0BiATIlpfa3WSe+TdNgFbc8/qw8c35bAaNWYJcCHh42zshgsaehAoGACDQh
    IniR2754V+4XLxIWcTTlXjDHSgn1T07rh+8fCE138WCV/HUe8wT5WeW8503gL9hJ
    Taq+Be6s2kf4s91dkTdADyGrfIMjlb+8x2mVnptUTM68xuay0MH7rlXNriWmoZ+z
    1Rshm/DgESJjQAI+k7LigL662liM1EFk/2ajJRECgYEAhJgSqp8MzvnWDzIEAG4z
    SCw+0oZFKZR8qMZt9XQMdMKnxjmhYhKcAweujy3wAHTN3IDk7Yt8+9+nZGQe/zkP
    1NXHLklQkPYFnPqDZ+r2bbX/IHTtdStSUyfM/70E2jDkXkCxij+4wLdJDLXlkdwv
    Va0/B49ooBPyzsStLHObXgo=
    -----END PRIVATE KEY-----
  domain.crt: |
    -----BEGIN CERTIFICATE-----
    MIIELzCCAxegAwIBAgIUAOmea0GVjVqJuirVytqg2q8N11gwDQYJKoZIhvcNAQEL
    BQAwgaYxCzAJBgNVBAYTAkRFMRAwDgYDVQQIDAdCYXZhcmlhMQ8wDQYDVQQHDAZN
    dW5pY2gxHTAbBgNVBAoMFFNreSBEZXV0c2NobGFuZCBHbWJIMQ8wDQYDVQQLDAZO
    ZXdDUk0xGzAZBgNVBAMMEnJlZGlzLmFscGFuYS5sb2NhbDEnMCUGCSqGSIb3DQEJ
    ARYYYWxwYW5hLmNoYXBoYWxrYXJAc2t5LmRlMB4XDTIzMDIxNjE0MzQzNloXDTI0
    MDIxNjE0MzQzNlowgaYxCzAJBgNVBAYTAkRFMRAwDgYDVQQIDAdCYXZhcmlhMQ8w
    DQYDVQQHDAZNdW5pY2gxHTAbBgNVBAoMFFNreSBEZXV0c2NobGFuZCBHbWJIMQ8w
    DQYDVQQLDAZOZXdDUk0xGzAZBgNVBAMMEnJlZGlzLmFscGFuYS5sb2NhbDEnMCUG
    CSqGSIb3DQEJARYYYWxwYW5hLmNoYXBoYWxrYXJAc2t5LmRlMIIBIjANBgkqhkiG
    9w0BAQEFAAOCAQ8AMIIBCgKCAQEApUMyEcHhzeYnepc62BQeFyjlVcsbIee3sJO2
    wp82UwmjrOMHXYFp2vZI6GwM9l7j7AIesCDaB4JduTkUTTBHwU2PXpJAOHCQQjG5
    kRXlfharTLNhemE7+8x7bNmYgRO6RlcY5NGyM/Tw9IkIc068+cl3l5OGjYMwFSM1
    +1rgkbUgyUaTSiZNHkscyPkdLjuLwZZ5bbYC0FyAl1KJpfHyYyldoiwVH7uiemOU
    ztjSxpz9RCA5MVvBWpg5enJwAGLp22CJkdwiPfBkIQ9yvhyMFEtWeVCvAYfWLBVl
    6KA6UozDnTxb1DArtaewdTvXoQ4yB8sbOB5M36omEKPZCP5RWQIDAQABo1MwUTAd
    BgNVHQ4EFgQUA83SBBZyZagYYiefVvudgc37wngwHwYDVR0jBBgwFoAUA83SBBZy
    ZagYYiefVvudgc37wngwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOC
    AQEAIiaLzi9cqkTRAVbQPjMhmLp0UWuQ78llnGFsf47rjxNozEcE5OFMFCb4W0aE
    EjG++Nj2Tupy8MRMLf89D/MaKBsLDJzShH8MqGDYl7MQkwMc5xyFSBxX0puSphml
    GkzmkrdK+e/TiTYcU42HGW/eOPtZdM2P4VD6GXYrrSkdonSTutTkA5V2DkcsMVV2
    2eLB0RWkWuxuu7ZF/dVNIQLe+2j9k37YJWiu0ZgEazO72wdZ39db3fFaHrDkrYR+
    Z/iy2xd9//+c8brz7lQZQ9idDnvfX8Aof4EL+BUVerrRV69MSYTqzbwy5LtWnRO4
    wdh9bCWwyRHrzhxeBisRfwVIYA==
    -----END CERTIFICATE-----