---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - namspace.yaml
  - configmap.yaml
  - service.yaml
namespace: redis
namePrefix: redis-
commonLabels:
  app.kubernetes.io/name: redis
  app.kubernetes.io/component: test-automation-jmeter-redis
  app.kubernetes.io/part-of: nft-jmeter-redis