---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - namspace.yaml
  - configmap.yaml
  - service.yaml
  - secret.yaml
namespace: influxdb
namePrefix: influxdb-
commonLabels:
  app.kubernetes.io/name: influxdb
  app.kubernetes.io/component: test-automation-jmeter-influxdb
  app.kubernetes.io/part-of: nft-jmeter-influxdb