apiVersion: v1
kind: Secret
metadata:
  name: secret
data:
  DOCKER_INFLUXDB_INIT_USERNAME: YWxwYW5h
  DOCKER_INFLUXDB_INIT_PASSWORD: aW5mbHV4ZGJAYWxwYW5h
  DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: U2NIQ2JkbzZBMmdvUTlhZlQzaUduaDRWb1pVdlZpRXdtSDhkcGNHV200NUIybWZBTjJuMUVNMzNvRzVvdHYyY0NUdmtpTzkyLUNGcEM5d0hwUVhOVlE9PQ==